name: Project deploy on cpanel
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  web-deploy:
    name: ğŸŒ» Deploy
    runs-on: ubuntu-latest
    steps:
    - name: â˜€ï¸Get latest code
      uses: actions/checkout@v2.1.0

    - name: ğŸ©¸ Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.FTP_SERVER }}
        ftp-username: ${{ secrets.FTP_USERNAME }}
        ftp-password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /public_html/deploying/
        git-ftp-args: --insecure
